/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package callerpackage;

import databasepackage.Person;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.Query;
import kayitpackage.KayitEkrani;

/**
 *
 * @author Grant
 */
public class CallerIdFrame extends javax.swing.JFrame {

    static Color lightBlue = new Color(223, 246, 247);
    static Color lightGreen = new Color(211, 245, 211);
    static Color lightestGreen = new Color(232, 250, 233);

    static JLabel callPhonePics[] = new JLabel[5];
    static JLabel callDatabasePics[] = new JLabel[5];
    
    static JLabel callTimes[] = new JLabel[5];
    
    static JLabel callNumbers[] = new JLabel[5];
    
    static JLabel callNames[] = new JLabel[5];
    
    static JPanel callPanels[] = new JPanel[5];
    
    static JLabel callSurnames[] = new JLabel[5];
        
    static JLabel callAdresses[] = new JLabel[5];
    
    static JLabel callNotes[] = new JLabel[5];
    
    static JLabel callNumbers2[] = new JLabel[5];
    
    static ImageIcon imgRing;
    static ImageIcon imgOffHook;
    static ImageIcon imgOnHook;

    static ImageIcon imgDatabaseIdle;
    static ImageIcon imgDatabaseFound;
    static ImageIcon imgDatabaseInsert;

    /**
     * Creates new form frmMain
     */
    public CallerIdFrame() {
        initComponents();

        // Make object arrays for referencing
        callPhonePics[1] = picLine1;
        callPhonePics[2] = picLine2;
        callPhonePics[3] = picLine3;
        callPhonePics[4] = picLine4;

        callTimes[1] = lbTime1;
        callTimes[2] = lbTime2;
        callTimes[3] = lbTime3;
        callTimes[4] = lbTime4;

        callNumbers[1] = lbNumber1;
        callNumbers[2] = lbNumber2;
        callNumbers[3] = lbNumber3;
        callNumbers[4] = lbNumber4;

        callNames[1] = lbName1;
        callNames[2] = lbName2;
        callNames[3] = lbName3;
        callNames[4] = lbName4;

        callSurnames[1] = lbName7;
        callSurnames[2] = lbName10;
        callSurnames[3] = lbName13;
        callSurnames[4] = lbName16;
        
        callAdresses[1] = lbName5;
        callAdresses[2] = lbName8;
        callAdresses[3] = lbName11;
        callAdresses[4] = lbName14;
        
        callNotes[1] = lbName6;
        callNotes[2] = lbName9;
        callNotes[3] = lbName12;
        callNotes[4] = lbName15;
        
        callNumbers2[1] = lbName17;
        callNumbers2[2] = lbName18;
        callNumbers2[3] = lbName19;
        callNumbers2[4] = lbName20;
        
        callPanels[1] = panLine1;
        callPanels[2] = panLine2;
        callPanels[3] = panLine3;
        callPanels[4] = panLine4;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLine1 = new javax.swing.JPanel();
        picLine1 = new javax.swing.JLabel();
        lbLine1 = new javax.swing.JLabel();
        lbTime1 = new javax.swing.JLabel();
        lbNumber1 = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        lbName5 = new javax.swing.JLabel();
        lbName6 = new javax.swing.JLabel();
        lbName7 = new javax.swing.JLabel();
        lbName17 = new javax.swing.JLabel();
        panLine2 = new javax.swing.JPanel();
        lbName2 = new javax.swing.JLabel();
        picLine2 = new javax.swing.JLabel();
        lbNumber2 = new javax.swing.JLabel();
        lbLine2 = new javax.swing.JLabel();
        lbTime2 = new javax.swing.JLabel();
        lbName8 = new javax.swing.JLabel();
        lbName9 = new javax.swing.JLabel();
        lbName10 = new javax.swing.JLabel();
        lbName18 = new javax.swing.JLabel();
        panLine3 = new javax.swing.JPanel();
        lbTime3 = new javax.swing.JLabel();
        lbNumber3 = new javax.swing.JLabel();
        picLine3 = new javax.swing.JLabel();
        lbLine3 = new javax.swing.JLabel();
        lbName3 = new javax.swing.JLabel();
        lbName11 = new javax.swing.JLabel();
        lbName12 = new javax.swing.JLabel();
        lbName13 = new javax.swing.JLabel();
        lbName19 = new javax.swing.JLabel();
        panLine4 = new javax.swing.JPanel();
        lbName4 = new javax.swing.JLabel();
        lbTime4 = new javax.swing.JLabel();
        picLine4 = new javax.swing.JLabel();
        lbNumber4 = new javax.swing.JLabel();
        lbLine4 = new javax.swing.JLabel();
        lbName14 = new javax.swing.JLabel();
        lbName15 = new javax.swing.JLabel();
        lbName16 = new javax.swing.JLabel();
        lbName20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arama Ekranı");
        setBackground(new java.awt.Color(255, 255, 255));

        panLine1.setBackground(new java.awt.Color(192, 192, 192));
        panLine1.setName("panLine1"); // NOI18N

        picLine1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sampleapplication/phoneOnHook.jpg"))); // NOI18N
        picLine1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbLine1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbLine1.setText("01");

        lbTime1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbTime1.setText("Zaman");

        lbNumber1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbNumber1.setText("Numara");

        lbName1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName1.setText("İsim");

        lbName5.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName5.setText("Adres");

        lbName6.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName6.setText("Not");

        lbName7.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName7.setText("Soyisim");

        lbName17.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName17.setText("2.Numara");

        javax.swing.GroupLayout panLine1Layout = new javax.swing.GroupLayout(panLine1);
        panLine1.setLayout(panLine1Layout);
        panLine1Layout.setHorizontalGroup(
            panLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLine1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLine1)
                .addGap(18, 18, 18)
                .addComponent(lbLine1)
                .addGap(18, 18, 18)
                .addComponent(lbTime1)
                .addGap(96, 96, 96)
                .addComponent(lbNumber1)
                .addGap(96, 96, 96)
                .addComponent(lbName1)
                .addGap(82, 82, 82)
                .addComponent(lbName7)
                .addGap(67, 67, 67)
                .addComponent(lbName5)
                .addGap(64, 64, 64)
                .addComponent(lbName6)
                .addGap(64, 64, 64)
                .addComponent(lbName17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panLine1Layout.setVerticalGroup(
            panLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLine1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLine1)
                    .addGroup(panLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumber1)
                        .addComponent(lbName1)
                        .addComponent(lbName5)
                        .addComponent(lbName6)
                        .addComponent(lbName7)
                        .addComponent(lbName17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        picLine1.getAccessibleContext().setAccessibleName("picLine1");
        lbLine1.getAccessibleContext().setAccessibleName("lbLine1");
        lbTime1.getAccessibleContext().setAccessibleName("lbTime1");
        lbNumber1.getAccessibleContext().setAccessibleName("lbNumber1");
        lbName1.getAccessibleContext().setAccessibleName("lbName1");

        panLine2.setBackground(new java.awt.Color(192, 192, 192));
        panLine2.setName("panLine2"); // NOI18N
        panLine2.setPreferredSize(new java.awt.Dimension(533, 55));

        lbName2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName2.setText("İsim");

        picLine2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sampleapplication/phoneOnHook.jpg"))); // NOI18N
        picLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbNumber2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbNumber2.setText("Numara");

        lbLine2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbLine2.setText("02");

        lbTime2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbTime2.setText("Zaman");

        lbName8.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName8.setText("Adres");

        lbName9.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName9.setText("Not");

        lbName10.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName10.setText("Soyisim");

        lbName18.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName18.setText("2.Numara");

        javax.swing.GroupLayout panLine2Layout = new javax.swing.GroupLayout(panLine2);
        panLine2.setLayout(panLine2Layout);
        panLine2Layout.setHorizontalGroup(
            panLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLine2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLine2)
                .addGap(18, 18, 18)
                .addComponent(lbLine2)
                .addGap(18, 18, 18)
                .addComponent(lbTime2)
                .addGap(96, 96, 96)
                .addComponent(lbNumber2)
                .addGap(96, 96, 96)
                .addComponent(lbName2)
                .addGap(84, 84, 84)
                .addComponent(lbName10)
                .addGap(63, 63, 63)
                .addComponent(lbName8)
                .addGap(67, 67, 67)
                .addComponent(lbName9)
                .addGap(63, 63, 63)
                .addComponent(lbName18)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panLine2Layout.setVerticalGroup(
            panLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLine2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLine2)
                    .addGroup(panLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumber2)
                        .addComponent(lbName2)
                        .addComponent(lbName10)
                        .addComponent(lbName8)
                        .addComponent(lbName9)
                        .addComponent(lbName18)))
                .addContainerGap())
        );

        picLine2.getAccessibleContext().setAccessibleName("picLine2");

        panLine3.setBackground(new java.awt.Color(192, 192, 192));
        panLine3.setName("panLine3"); // NOI18N

        lbTime3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbTime3.setText("Zaman");

        lbNumber3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbNumber3.setText("Numara");

        picLine3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sampleapplication/phoneOnHook.jpg"))); // NOI18N
        picLine3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbLine3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbLine3.setText("03");

        lbName3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName3.setText("İsim");

        lbName11.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName11.setText("Adres");

        lbName12.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName12.setText("Not");

        lbName13.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName13.setText("Soyisim");

        lbName19.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName19.setText("2.Numara");

        javax.swing.GroupLayout panLine3Layout = new javax.swing.GroupLayout(panLine3);
        panLine3.setLayout(panLine3Layout);
        panLine3Layout.setHorizontalGroup(
            panLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLine3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLine3)
                .addGap(18, 18, 18)
                .addComponent(lbLine3)
                .addGap(18, 18, 18)
                .addComponent(lbTime3)
                .addGap(96, 96, 96)
                .addComponent(lbNumber3)
                .addGap(96, 96, 96)
                .addComponent(lbName3)
                .addGap(83, 83, 83)
                .addComponent(lbName13)
                .addGap(62, 62, 62)
                .addComponent(lbName11)
                .addGap(71, 71, 71)
                .addComponent(lbName12)
                .addGap(63, 63, 63)
                .addComponent(lbName19)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panLine3Layout.setVerticalGroup(
            panLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLine3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picLine3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTime3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumber3)
                        .addComponent(lbName3)
                        .addComponent(lbName13)
                        .addComponent(lbName11)
                        .addComponent(lbName12)
                        .addComponent(lbName19)))
                .addContainerGap())
        );

        panLine4.setBackground(new java.awt.Color(192, 192, 192));
        panLine4.setName("panLine4"); // NOI18N

        lbName4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName4.setText("İsim");

        lbTime4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbTime4.setText("Zaman");

        picLine4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sampleapplication/phoneOnHook.jpg"))); // NOI18N
        picLine4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbNumber4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbNumber4.setText("Numara");

        lbLine4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbLine4.setText("04");

        lbName14.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName14.setText("Adres");

        lbName15.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName15.setText("Not");

        lbName16.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName16.setText("Soyisim");

        lbName20.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lbName20.setText("2.Numara");

        javax.swing.GroupLayout panLine4Layout = new javax.swing.GroupLayout(panLine4);
        panLine4.setLayout(panLine4Layout);
        panLine4Layout.setHorizontalGroup(
            panLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLine4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLine4)
                .addGap(18, 18, 18)
                .addComponent(lbLine4)
                .addGap(18, 18, 18)
                .addComponent(lbTime4)
                .addGap(96, 96, 96)
                .addComponent(lbNumber4)
                .addGap(96, 96, 96)
                .addComponent(lbName4)
                .addGap(86, 86, 86)
                .addComponent(lbName16)
                .addGap(64, 64, 64)
                .addComponent(lbName14)
                .addGap(66, 66, 66)
                .addComponent(lbName15)
                .addGap(64, 64, 64)
                .addComponent(lbName20)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panLine4Layout.setVerticalGroup(
            panLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLine4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picLine4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTime4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumber4)
                        .addComponent(lbName4)
                        .addComponent(lbName16)
                        .addComponent(lbName14)
                        .addComponent(lbName15)
                        .addComponent(lbName20)))
                .addContainerGap())
        );

        jButton1.setText("Yeni Kayıt Oluştur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
            .addComponent(panLine3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panLine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(515, 515, 515))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        KayitEkrani kayitEkrani = new KayitEkrani();
        kayitEkrani.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallerIdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallerIdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallerIdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallerIdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CallerIdFrame().setVisible(true);
            }
        });

        imgRing = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/phoneRing.jpg"));
        imgOffHook = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/phoneOffHook.jpg"));
        imgOnHook = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/phoneOnHook.jpg"));

        imgDatabaseIdle = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/databaseIdle.jpg"));
        imgDatabaseFound = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/databaseFound.jpg"));
        imgDatabaseInsert = new ImageIcon(CallerIdFrame.class.getResource("/sampleapplication/databaseInsert.jpg"));
        // Start receiving thread
        try {
            Thread receiver = new ReceiverThread(3520);
            receiver.start();
        } catch (Exception ex) {
            infoBox("Other program/service has already been bound to required port. Close ELPopup if it is running.", "Error");
            System.exit(0);
        }

    }

    public static void handleData(String inData) {

        String myData = inData;
        String command;
        Integer myLine = 0;
        String myType = "";
        String myIndicator = "";
        String myDuration = "";
        String myCheckSum = "";
        String myRings = "";
        String myDateTime = "";
        String myNumber = "";
        String myName = "";

        //Parse
        Pattern myPattern = Pattern.compile(".*(\\d\\d) ([IO]) ([ES]) (\\d{4}) ([GB]) (.)(\\d) (\\d\\d/\\d\\d \\d\\d:\\d\\d [AP]M) (.{8,15})(.*)");
        Matcher matcher = myPattern.matcher(myData);

        if (matcher.find() == true) {

            myLine = Integer.parseInt(matcher.group(1));
            myType = matcher.group(2);

            if (myType.equals("I") || myType.equals("O")) {
                myIndicator = matcher.group(3);
                myDuration = matcher.group(4);
                myCheckSum = matcher.group(5);
                myRings = matcher.group(6);
                myDateTime = matcher.group(8);
                myName = matcher.group(10);
                myNumber = matcher.group(9);
            }

        }

        Pattern myPatternDetailed = Pattern.compile(".*(\\d\\d) ([NFR]) {13}(\\d\\d/\\d\\d \\d\\d:\\d\\d:\\d\\d)");
        Matcher matcherDetailed = myPatternDetailed.matcher(myData);

        if (matcherDetailed.find() == true) {

            myLine = Integer.parseInt(matcherDetailed.group(1));
            myType = matcherDetailed.group(2);

            if (myType.equals("N") || myType.equals("F") || myType.equals("R")) {
                myDateTime = matcherDetailed.group(3);
            }

        }

        command = myType + myIndicator;

          // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Catering_Otomasyon_1.0.0PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT p FROM Person p WHERE p.tel=:pTel");
        q.setParameter("pTel", myNumber);
        Person person = null;
        try{
            person = (Person)q.getSingleResult();
        }
        catch(NoResultException e){
            q = em.createQuery("SELECT p FROM Person p WHERE p.tel2=:pTel2");
            q.setParameter("pTel2", myNumber);
            try{
                person = (Person)q.getSingleResult();
            }
            catch(NoResultException en){
                person = new Person();
            }
        }
        System.out.println(person.getAd());
        
        // Display data in window
        switch (command) {

            case "R":

                // Incoming Call
                // Change picture of phone to ringing
                callPhonePics[myLine].setIcon(imgRing);

                // Light up panel green for incoming call
                callPanels[myLine].setBackground(lightGreen);

                // Show time on panel
                callTimes[myLine].setText(myDateTime);

                // Show name and number on panel
                if(person.getTel() == null){
                    callNumbers[myLine].setText(myNumber);
                }
                else{
                    callNumbers[myLine].setText(person.getTel());
                }
                
                callNumbers2[myLine].setText(person.getTel2());
                callNames[myLine].setText(person.getAd());
                callSurnames[myLine].setText(person.getSoyad());
                callAdresses[myLine].setText(person.getAdres());
                callNotes[myLine].setText(person.getNotunuz());
                
                break;

            case "IS":

                // Ring answered
                // Light-up panel green for incoming call
                callPanels[myLine].setBackground(lightestGreen);

                // Show time on panel
                callTimes[myLine].setText(myDateTime);

                // Show name and number on panel
                if(person.getTel() == null){
                    callNumbers[myLine].setText(myNumber);
                }
                else{
                    callNumbers[myLine].setText(person.getTel());
                }
                
                callNames[myLine].setText(person.getAd());
                callSurnames[myLine].setText(person.getSoyad());
                callAdresses[myLine].setText(person.getAdres());
                callNotes[myLine].setText(person.getNotunuz());
                callNumbers2[myLine].setText(person.getTel2());
                
                break;

            case "F":

                // Phone pickup
                // Change picture of phone to off hook
                callPhonePics[myLine].setIcon(imgOffHook);

                break;

            case "N":

                // Phone hangup
                callPanels[myLine].setBackground(Color.lightGray);

                // Change picture of phone to not-ringing
                callPhonePics[myLine].setIcon(imgOnHook);

                break;

            case "IE":
                break;
            case "OS":

                // Outgoing Call
                // Change picture of phone to off hook
                callPhonePics[myLine].setIcon(imgOffHook);

                callPanels[myLine].setBackground(lightBlue);

                // Show time on panel
                callTimes[myLine].setText(myDateTime);
                //panels(intLine).lbTime.Text = MyTime

                // Show name and number on panel
                if(person.getTel() == null){
                    callNumbers[myLine].setText(myNumber);
                }
                else{
                    callNumbers[myLine].setText(person.getTel());
                }
                
                callNames[myLine].setText(person.getAd());
                callSurnames[myLine].setText(person.getSoyad());
                callAdresses[myLine].setText(person.getAdres());
                callNotes[myLine].setText(person.getNotunuz());
                callNumbers2[myLine].setText(person.getTel2());

                break;

            case "OE":

                break;
        }

    }

    public static void infoBox(String infoMessage, String location) {
        JOptionPane.showMessageDialog(null, infoMessage, location, JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private static javax.swing.JLabel lbLine1;
    private static javax.swing.JLabel lbLine2;
    private static javax.swing.JLabel lbLine3;
    private static javax.swing.JLabel lbLine4;
    private static javax.swing.JLabel lbName1;
    private static javax.swing.JLabel lbName10;
    private static javax.swing.JLabel lbName11;
    private static javax.swing.JLabel lbName12;
    private static javax.swing.JLabel lbName13;
    private static javax.swing.JLabel lbName14;
    private static javax.swing.JLabel lbName15;
    private static javax.swing.JLabel lbName16;
    private static javax.swing.JLabel lbName17;
    private static javax.swing.JLabel lbName18;
    private static javax.swing.JLabel lbName19;
    private static javax.swing.JLabel lbName2;
    private static javax.swing.JLabel lbName20;
    private static javax.swing.JLabel lbName3;
    private static javax.swing.JLabel lbName4;
    private static javax.swing.JLabel lbName5;
    private static javax.swing.JLabel lbName6;
    private static javax.swing.JLabel lbName7;
    private static javax.swing.JLabel lbName8;
    private static javax.swing.JLabel lbName9;
    private static javax.swing.JLabel lbNumber1;
    private static javax.swing.JLabel lbNumber2;
    private static javax.swing.JLabel lbNumber3;
    private static javax.swing.JLabel lbNumber4;
    public static javax.swing.JLabel lbTime1;
    private static javax.swing.JLabel lbTime2;
    private static javax.swing.JLabel lbTime3;
    private static javax.swing.JLabel lbTime4;
    private static javax.swing.JPanel panLine1;
    private static javax.swing.JPanel panLine2;
    private static javax.swing.JPanel panLine3;
    private static javax.swing.JPanel panLine4;
    private static javax.swing.JLabel picLine1;
    private static javax.swing.JLabel picLine2;
    private static javax.swing.JLabel picLine3;
    private static javax.swing.JLabel picLine4;
    // End of variables declaration//GEN-END:variables
}
